### PR TITLE
Testing to do list part 2

### PR DESCRIPTION
**Pull request by ameerhamzakhalid**
###  **We added three more functions:**

1.     Add a function for testing editing the task description.
2.     Add a function for testing the updating of an item's 'completed' status.
3.     Add the "Clear all completed" function test.

### CODE REVIEW

**Review by OyePriscilla — CHANGES_REQUESTED** [review]
Hi @ameerhamzakhalid and @rugwizangoga  😃, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

so-close-so-close-seth-meyers

## Highlights
Github flow observed✔️
Linters checks passed ✔️ 

## Required Changes ♻️

- [x] Kindly install the jest framework according to the project [requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/tests_2.md), I couldn't affirm the awesome test you've written if it is passed or not. Thanks. 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ameerhamzakhalid** [comment]
Hi @OyePriscilla , thank you so much for your kind response, But according to best of my knowledge the jest framework is already installed according to the requirement functions i.e editing task description, updating an item's 'completed' status and Clear all completed. Kindly run `npm run start` for testing.

**Comment by OyePriscilla** [comment]
Hi @ameerhamzakhalid and @rugwizangoga, `npm run start` is to start your server but for the test function you need to run `npm test`. Actually your `package.json` file supposed to have the jest installed as part of the dependencies. 💁

**Comment by ameerhamzakhalid** [comment]
Yes exactly that's what im saying thay package.json does contains jest

**Review by cynthiainga — APPROVED** [review]
Hi @ameerhamzakhalid & @rugwizangoga, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] All tests are passing 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
